config/routes.rb
Cmms::Application.routes.draw do
  get 'control_panel/index'

  resources :roles

  resources :categories

  resources :facilities

  devise_for :users
  scope "/admin" do
    resources :users
    
    get 'control_panel', controller: 'control_panel', action: :index
  end
  
  get 'reports/by_address', controller: 'reports', action: :by_address

  get 'reports/by_status', controller: 'reports', action: :by_status

  get 'reports/by_category', controller: 'reports', action: :by_category
  
  get 'reports/closed_items', controller: 'reports', action: :closed_items
  
  get 'reports/closed_items_by_category', controller: 'reports', action: :closed_items_by_category
  
  get 'reports/closed_items_by_status', controller: 'reports', action: :closed_items_by_status
  
  get 'reports', controller: 'reports', action: :by_address
  
  get 'contact', controller: 'contact', action: :index

  resources :properties
  
  resources :service_requests

  authenticated :user do
    root :to => 'service_requests#index', as: :authenticated_root
  end
  root :to => 'service_requests#index'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!
  
  def by_address
    @service_requests = ServiceRequest.where("status != ?", 2) 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @service_requests }
    end
  end

  def by_status
    @service_requests = ServiceRequest.where("status != ?", 2)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @service_requests }
    end
  end

  def by_category
    @service_requests = ServiceRequest.where("status != ?", 2)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @service_requests }
    end
  end
  
  def closed_items
    if params[:search] && params[:page]
      @service_requests = ServiceRequest.where("status = ?", 2).search_by_address(params[:search], params[:page], 75, "ID")
    elsif !params[:search]
      @service_requests = ServiceRequest.where("status = ?", 2).search_by_address("", params[:page], 75, "ID")
    elsif !params[:page]
      @service_requests = ServiceRequest.where("status = ?", 2).search_by_address(params[:search], 1, 75, "ID")
    else
      @service_requests = ServiceRequest.where("status = ?", 2).search_by_address("", 1, 75, "ID")
    end 
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @service_requests }
    end
  end
  
  def closed_items_by_category
    if params[:search] && params[:page]
      @service_requests = ServiceRequest.where("status" => 2).search_by_category(params[:search], params[:page], 75, "ID")
    elsif !params[:search]
      @service_requests = ServiceRequest.where("status" => 2).search_by_category("", params[:page], 75, "ID")
    elsif !params[:page]
      @service_requests = ServiceRequest.where("status" => 2).search_by_category(params[:search], 1, 75, "ID")
    else
      @service_requests = ServiceRequest.where("status" => 2).search_by_category("", 1, 75, "ID")
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @service_requests }
    end
  end
  
  def closed_items_by_status
    if params[:search] && params[:page]
      @service_requests = ServiceRequest.where("status" => 2).search_by_status(params[:search], params[:page], 75, "ID")
    elsif !params[:search]
      @service_requests = ServiceRequest.where("status" => 2).search_by_status("", params[:page], 75, "ID")
    elsif !params[:page]
      @service_requests = ServiceRequest.where("status" => 2).search_by_status(params[:search], 1, 75, "ID")
    else
      @service_requests = ServiceRequest.where("status" => 2).search_by_status("", 1, 75, "ID")
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @service_requests }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_work_orders_list.html.erb
<p class="text-right" style="margin-top:5px;">
	<span class="badge badge-dark">M</span><small> Maintenance &nbsp;</small>
    <span class="badge badge-dark"> I </span><small> Irrigations &nbsp;</small>
    <span class="badge badge-dark">G</span><small> Grounds &nbsp;</small>
    <span class="badge badge-dark">C</span><small> Code Compliance &nbsp;</small>
    
    |&nbsp;
  	<%= link_to 'New work order', new_service_request_path %>
</p>

<small class="pull-right"> Showing a total of <%= @service_requests.length %> records </small>
<table id="all_items" class="table table-striped table-hover">
<thead>  
	<tr>
		<th>Address</th>
		<th>Title</th>
		<th>Description</th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
</thead>
<% @service_requests.each do |service_request| %>
<tbody>
	<tr>
		<td><%= service_request.address %></td>
		<td><%= truncate(service_request.title) %></td>
		<td><%= truncate(service_request.description, length: 50) %></td>
		<td>
			<% if(service_request.status == 2) # if(archived) %>
				<hidden hidden>closed</hidden>
            	<span class="label label-light" data-toggle="tooltip" data-placement="top" title="Closed">&nbsp;</span>
            <% elsif (service_request.status == 3) # if(pending) %>
            	<hidden hidden>pending</hidden>
            	<span class="label label-yellow" data-toggle="tooltip" data-placement="top" title="Pending">&nbsp;</span>
            <% else #if(open) %>
            	<hidden hidden>open</hidden>
            	<span class="label label-success" data-toggle="tooltip" data-placement="top" title="Open">&nbsp;</span>
            <% end #ends if(statuses) %>
		</td>
		<td>
			<% if(service_request.category.id == 1) %>
				<hidden hidden>maintenance</hidden>
            	<span class="badge badge-dark" data-toggle="tooltip" data-placement="top" title="Maintenance">M</span>
            <% elsif (service_request.category.id == 2)%>
            	<hidden hidden>Irrigations</hidden>
            	<span class="badge badge-dark" data-toggle="tooltip" data-placement="top" title="Irrigations"> I </span>
            <% elsif (service_request.category.id == 3) %>
            	<hidden hidden>Grounds</hidden>
            	<span class="badge badge-dark" data-toggle="Grounds" data-placement="top" title="Grounds">G</span>
            <% else %>
            	<hidden hidden>code compliance</hidden>
            	<span class="badge badge-dark" data-toggle="tooltip" data-placement="top" title="Code Compliance"> C </span>
            <% end %>
		</td>
		<td>
			<% if(service_request.status != 2) #if(not archived) %>
				<% if(service_request.alert_date < Date.today) #if(expired) %>
					<hidden hidden>expired</hidden>
	              <span class="label label-danger" data-toggle="tooltip" data-placement="top" title="Expired on: <%= service_request.alert_date %>"><i class="fa fa-exclamation"></i></span>
	            <% elsif (service_request.warning_date <= Date.today) #if(expiring) %>
	            	<hidden hidden>expiring</hidden>
	              <span class="label label-warning" data-toggle="tooltip" data-placement="top" title="Expiring"><i class="fa fa-exclamation"></i></span>
	            <% end %>
			<% end %>
		</td>
		<td><%= link_to 'View', service_request %></td>
		<td><%= link_to 'Edit', edit_service_request_path(service_request) %></td>
		<td><%= link_to 'Delete', service_request, confirm: 'Are you sure?', method: :delete %></td>
	</tr>
<% end %>
</tbody>
</table>

<% content_for :js_scripts do %>
  	<%= javascript_include_tag "jquery.searchable" %>

  	<script type="text/javascript">
	    $(document).ready(function() {
			$('#all_items' ).searchable({
					searchField   : '#search_by_id'
				});
	    });
	</script>

<% end %>

app/views/reports/closed_items_by_category.erb
<%= content_for(:title, "Closed Work Orders by Address") %>

<p><span class="help-block">Search functionality is <b>ONLY</b> working with the address field for closed items.</span></p>
<br/>

<%= link_to "Hide closed items", reports_path, :class => "pull-right" %>

<div class="form-group">
	<%= form_tag "/reports/closed_items_by_category", :method => 'get' do %>
	  <%= content_tag :div, :class => "form-group" do %>
	    <%= text_field_tag :search, params[:search], :class => "form-control input-lg", :placeholder => "Type the category here and hit Enter " %>
	  <% end %>
	<% end %>
</div>

<%= render "work_orders_list" %>
<div class="row text-center"><%= will_paginate @service_requests, previous_label: h("<"), next_label: h(">") %></div>


<script>
$(function() {
	var availableOptions = [ 
	{value: "1", label:"Maintenance"}, 
	{value: "2", label:"Irrigations"}, 
	{value: "3", label:"Grounds"}
	];
	$( "#search" ).autocomplete({
		source: availableOptions,
		focus: function( event, ui ) {
        $( "#search" ).val( ui.item.label );
            return false;
        },
        select: function( event, ui ) {
        $( "#search" ).val( ui.item.label );
 
        return false;
      }
	});
});
</script>