config/routes.rb
Cmms::Application.routes.draw do
  get 'control_panel/index'

  resources :roles

  resources :categories

  resources :facilities

  devise_for :users
  scope "/admin" do
    resources :users
    
    get 'control_panel', controller: 'control_panel', action: :index
  end
  
  get 'reports/by_address', controller: 'reports', action: :by_address

  get 'reports/by_status', controller: 'reports', action: :by_status

  get 'reports/by_category', controller: 'reports', action: :by_category
  
  get 'reports/closed_items', controller: 'reports', action: :closed_items
  
  get 'reports/closed_items_by_category', controller: 'reports', action: :closed_items_by_category
  
  get 'reports/closed_items_by_status', controller: 'reports', action: :closed_items_by_status
  
  get 'reports', controller: 'reports', action: :by_address
  
  get 'contact', controller: 'contact', action: :index

  resources :properties
  
  resources :service_requests

  authenticated :user do
    root :to => 'service_requests#index', as: :authenticated_root
  end
  root :to => 'service_requests#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<html>
<head>
	<title>InterAccess Systems - Service Requests</title>
	
	<!-- Meta -->
	<meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1.0" name="viewport">
	<meta content="InterAccess Systems Work Orders application" name="description">
	<meta content="Dario Landeros" name="author">
	
	<%= javascript_include_tag "application" %>

	<%= stylesheet_link_tag "bootstrap", :media => "all" %>
	<%= stylesheet_link_tag "style", :media => "all" %>
	<%= stylesheet_link_tag "print", :media => "print" %>
	<%= stylesheet_link_tag "custom", :media => "all" %>
	<%= stylesheet_link_tag "blue", :media => "all" %>
	<%= stylesheet_link_tag "iphone-style", :media => "all" %>
	<%= stylesheet_link_tag "font-awesome", :media => "all" %>
	<%= stylesheet_link_tag "pagination", :media => "all" %>
	
	<%= yield(:header) %>
	<%= csrf_meta_tags %>
	
	<!-- Latest compiled and minified CSS 
	<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css"> -->
</head>
<body>
	<div id="wrapper">
		<!--=== Header ===-->
		<div class="header">
		    <!--=== Topbar ===-->
			<div class="topbar">
	            <div class="container">
	                <!-- Topbar Navigation -->
	                <ul class="loginbar pull-right"> 
	                	<li>
							<% if user_signed_in? %>
									<small>Hi,</small> <%= link_to current_user.email, edit_user_registration_path, :style => 'text-transform: none; padding: 0 0;' %> 
									<small>&nbsp; Not you?</small>
								<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
							  <% else %>
							  		<%= link_to "Sign in", new_session_path(resource_name) %>
							  <% end %>
						</li>
						<li class="topbar-devider"></li>
	                    <li><%= link_to "Help", contact_path %></li>        
	                </ul>
	                <!-- End Topbar Navigation -->
	            </div>
	        </div>
		    <!--=== End Topbar ===-->
		    <!--=== Navbar ===-->
		    <div class="navbar navbar-default" role="navigation">
				<div class="container">
					<!--=== Navbar Header ===-->
		        	<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                            <span class="sr-only">Toggle navigation</span> <span class="fa fa-bars"></span>
                        </button>
						<%= link_to image_tag("iaslogo.png", :style => 'margin-top:-34px; margin-left:-18px'), :root, :id => 'logo_container' %>
					</div>
					<!--=== End Navbar Header ===-->
					<!--=== Navbar Links ===-->
					<div class="collapse navbar-collapse navbar-responsive-collapse">
						<ul class="nav navbar-nav">
							<li class="<%= (controller_name == 'service_requests') ? "active" : "" %>" >
								<%= link_to "Home", :root %></li>
							<% if user_signed_in? %>
							<li class="<%= (controller_name == "reports") ? "dropdown active" : "dropdown" %>" >
							  <a href="#" id="dLabel" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							    Reports
							  </a>
							  <ul class="dropdown-menu" aria-labelledby="dLabel">
							    <li><%= link_to "By Address", reports_path %></li>
								<li><%= link_to "By Status", "/reports/by_status" %></li>
								<li><%= link_to "By Category", "/reports/by_category" %></li>
							  </ul>
							</li>
							<li class="<%= (controller_name == 'control_panel') ? "active" : "" %>">
								<% link_to "Control panel", control_panel_path %></li>
							<% end %>
							<li class="<%= (controller_name == 'contact') ? "active" : "" %>">
								<%= link_to "Contact", contact_path %></li>
						</ul>
					</div>
					<!--=== End Navbar Links ===-->
				</div>
		    </div>
		    <!--=== End Navbar ===-->
		</div>
		<!--=== End Header ===-->
		<!--=== Title / Breadcrumbs ===-->
		<div class="breadcrumbs">
			<div class="container">
				<h1 class="pull-left"><%= yield(:title) %></h1>
				<ul class="pull-right breadcrumb">
				</ul>
			</div><!--/container-->
		</div>
		
		<% flash.each do |type, message| %>
		  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade in">
		    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
		    <%= message %>
		  </div>
		<% end %>
		
		<!--=== End Title / Breadcrumbs ===-->		
		<div class="container content">
			<%= yield %>
		</div>
		<!--=== Footer ===-->
		<div class="footer sticky-footer">
			<div class="container">
				<div class="row">
					<p class="text-muted credit text-center">
						All rights reserved to <a href="http://www.ias1.com">InterAccess Systems</a> ©
		                        <a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a></p>
				</div>
			</div>
		</div>
		<!--=== End Footer ===-->
	</div>
	<!-- Latest compiled and minified JavaScript -->

	<%= javascript_include_tag "jquery-ui.js" %>
	<%= javascript_include_tag "bootstrap.min.js" %>
	<%= javascript_include_tag "spin.min.js" %>
	<%= javascript_include_tag "ladda.min.js" %>
	<%= javascript_include_tag "iphone-style-checkboxes.js" %>
	

	<script type="text/javascript">
	    $(document).ready(function() {
	    	App.init();
	      	$(':checkbox').iphoneStyle({
			  checkedLabel: 'YES',
			  uncheckedLabel: 'NO'
			});
			$(".alert-dismissible").fadeTo(2000, 500).slideUp(500, function(){
			    $(".alert-dismissible").alert('close');
			});
			$('[data-toggle="tooltip"]').tooltip()
	    });
	</script>
	<%= yield(:js_scripts) %>
</body>
</html>